
services:
  # 서버 (Planning Poker Backend)
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: planning-poker-server
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
    networks:
      - planning-poker-network
    restart: unless-stopped

  # 클라이언트 (Planning Poker Frontend)
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        - VITE_API_BASE_URL=
        - VITE_WEBSOCKET_URL=
    container_name: planning-poker-client
    networks:
      - planning-poker-network
    restart: unless-stopped

  # MongoDB (Database)
  mongodb:
    image: mongo:7
    container_name: planning-poker-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=planning_poker
    ports:
      - "27017:27017"
    volumes:
      - planning-poker-data:/data/db
    networks:
      - planning-poker-network
    restart: unless-stopped

  # MongoDB UI (Modern - Mongoku)
  mongoku:
    image: huggingface/mongoku:latest
    container_name: planning-poker-mongoku
    environment:
      - MONGOKU_DEFAULT_HOST=mongodb://admin:password123@mongodb:27017/
    ports:
      - "3100:3100"
    depends_on:
      - mongodb
    networks:
      - planning-poker-network
    restart: unless-stopped

  # MongoDB UI (Classic - Mongo Express) - backup option
  mongo-express:
    image: mongo-express:latest
    container_name: planning-poker-mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_OPTIONS_READONLY=true
    depends_on:
      - mongodb
    networks:
      - planning-poker-network
    restart: unless-stopped

  # Nginx (Reverse Proxy)
  nginx:
    image: nginx:alpine
    container_name: planning-poker-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
      - client
      - mongodb
    networks:
      - planning-poker-network
    restart: unless-stopped

networks:
  planning-poker-network:
    driver: bridge

volumes:
  planning-poker-data: