
services:
  # 서버 (Planning Poker Backend)
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: planning-poker-server
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
    networks:
      - planning-poker-network
    restart: unless-stopped

  # 클라이언트 (Planning Poker Frontend)
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost/api
        - VITE_WEBSOCKET_URL=ws://localhost
    container_name: planning-poker-client
    networks:
      - planning-poker-network
    restart: unless-stopped

  # Nginx (Reverse Proxy)
  nginx:
    image: nginx:alpine
    container_name: planning-poker-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
      - client
    networks:
      - planning-poker-network
    restart: unless-stopped

networks:
  planning-poker-network:
    driver: bridge

volumes:
  planning-poker-data: